Updates to support High Sierra and later brew versions
oddhill/oddenvironment pull request #22
Opened 2017-11-15 15:07 UTC by AdamGerthel

2017-11-15 15:15 UTC, AdamGerthel commented
Råkade visst få med ändringen om att alltid köra senaste long-term-support-versionen av node i samma pull request, men det kanske inte är hela världen..

2017-11-15 19:46 UTC, olofbokedal requested changes
Finns det någon dokumentation från Homebrew som säger att man ska köra with-httpd istället för with-apache för High Sierra?

Vi borde behålla en specifik version för nvm, lts kommer installera olika beroende på när man kör oddenv.

2017-11-15 21:29 UTC, AdamGerthel commented
Jag orkade inte skriva på engelska när jag visste att det skulle bli 100% internt :)

> Finns det någon dokumentation från Homebrew som säger att man ska köra with-httpd istället för with-apache för High Sierra?

Nej, men när man kör "with-apache" så påpekar Homebrew att det är förlegat. Det är alltså egentligen inte alls High Sierra-specifikt. Enbart ändringen i PHP är det. Skulle egentligen ha blivit flera issues, men jag lyckades inte göra pull requests för specifika commits när de låg på samma branch.

> Vi borde behålla en specifik version för nvm, lts kommer installera olika beroende på när man kör oddenv.

Jag tycker inte att det gör något, jag har alltid ett gäng olika versioner av node installerat, och man växlar med NVM beroende på projekt. Juste nu så underhålls inte oddenv så mycket, och node-versionen ligger efter hela tiden. @NormySan kanske har en åsikt i saken?

2017-11-16 05:30 UTC, olofjohansson commented
Ok, då är jag med på ändringarna gällande PHP. Vill nämligen minnas att det vid lansering av Sierra blev rekommenderat att köra med with-apache istället men varnar den nu så är det inga konstigheter.

Låter @NormySan svara på det gällande nvm då, även där vill jag minnas att vi har velat säkerställa samma version för alla men det kanske inte gäller längre.

2017-11-16 05:31 UTC, olofjohansson commented
Jag är sugen på att göra hela odd env förlegad egentligen och istället tillhandahålla ett script som typ konfigurerar PHP, MYSQL och Apache initialt, men sen får varje person själv ta hand om sin miljö. Tror det hade sparat oss mycket huvudvärk och folk bör vara kompetenta nog att kunna installera något utöver ovanstående ifall man har behov.

Men det är en annan diskussion.. :)

2017-11-16 07:15 UTC, AdamGerthel commented
> Ok, då är jag med på ändringarna gällande PHP. Vill nämligen minnas att det vid lansering av Sierra blev rekommenderat att köra med with-apache istället men varnar den nu så är det inga konstigheter.

Stämmer nog bra, för Homebrew slutade kompilera .so-filen för php som default om man inte körde "with-apache". Det hade nog inte med Sierra att göra då heller, utan att PHP-versionen var så gammal att man ansåg bla bla bla (orkade inte läsa allt i den tråden). Nu heter det tydligen inte apache i Homebrew längre, utan httpd. Jag tror att då som nu så är det ytterst sällan någon behöver installera oddenv från scratch, och oftast sammanfaller det med OS-uppdateringar, och då kopplar man ihop att felen har med det att göra, men är egentligen oberoende.

> Jag är sugen på att göra hela odd env förlegad egentligen och istället tillhandahålla ett script som typ konfigurerar PHP, MYSQL och Apache initialt, men sen får varje person själv ta hand om sin miljö. Tror det hade sparat oss mycket huvudvärk och folk bör vara kompetenta nog att kunna installera något utöver ovanstående ifall man har behov.

Förstår det, kan ifs tycka, nu när jag blev tvungen att kolla på vad oddenv gör, att det är en rätt enkel och slimmad grej, bara det att man skulle behöva lägga ett par dagar om året på underhåll.

Man vill ju helst ha en "set-it-and-forget-it"-lösning som utvecklare, men det innebär att någon måste underhålla den. Anyway, off topic ja :)

2017-12-13 16:50 UTC, NormySan commented
Vi vill gärna alltid ha senaste LTS versionen av node, det är så enkelt att byta med nvm om man behöver köra en äldre version så lika bra att oddenv alltid tar den senaste som är LTS release.

2017-12-14 05:39 UTC, olofbokedal approved these changes

2017-12-14 05:39 UTC, merged